name: Deployment of the User application API

on:
  push:
    branches: ["main"]

jobs:
  deploy-business-application-api:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Deploy the latest version of Restazo User API
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 5m
          script: |
            cd ~/Restazo/user.api
            git checkout main
            git pull origin main
            npm ci
            npm run build
            pm2 restart restazo-user-api
